Repository streamnative/kop, pull requests merged in 2020-12, with the labels that each got.

#244 Support CreateTopics request
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedCreateTopics.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature

#251 Support DescribeConfigs request
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaLogConfig.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature

#260 make allowAutoTopicCreation work
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Labels: triage/week-50

#264 Add tests to verify KoP with Confluent Schema Registry
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java
Labels: triage/week-51

#265 update lookup cache when onload & unload
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Labels: triage/week-45, type/bug

#268 remove null future cache from consumerTopicManagers
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Labels: triage/week-45, type/bug

#270 change auto read log to debug
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
Labels: triage/week-51

#272 Add the test framework for Kafka Streams
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaStreamsTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KafkaStreamsTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/TestCondition.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/TestUtils.java
Labels: triage/week-51

#274 Fix topic auto created when using Kafka AdminClient to get metadata
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: triage/week-51, type/bug

#279 using the first entry, index 0 as base offset
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageRecordUtils.java
Labels: triage/week-51, type/bug

#278 Bump pulsar to 2.7.0
  kafka-impl/pom.xml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaBrokerStarter.java
  pom.xml
  tests/pom.xml
Labels: dependencies

#281 Bump version to 2.8.0-SNAPSHOT
  kafka-impl/pom.xml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  pom.xml
  tests/pom.xml
Labels: dependencies

#292 upgrade pulsar dependency
  pom.xml
Labels: dependencies, triage/week-52

#267 remove unnecessary topics cache for Topic Manager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Labels: triage/week-51, type/bug

#293 Fix broken tests caused by static lookup cache
  .github/workflows/pr-test.yml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespacePulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottlePulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledPulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/PulsarAuthEnabledTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTablePulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableTestBase.java
Labels: type/bug
