Repository streamnative/kop, pull requests merged in 2021-03, with the labels that each got.

#391 change pulsar dependency jars to provided scope to reduce nar package size
  pom.xml
Labels: area/build, release/2.7.0.x

#387 Remove outdated files for standalone KoP service
  kafka-impl/conf/bookkeeper.conf
  kafka-impl/conf/global_zookeeper.conf
  kafka-impl/conf/kop.conf
  kafka-impl/conf/kop_env.sh
  kafka-impl/conf/kop_standalone.conf
  kafka-impl/conf/log4j2.yaml
  kafka-impl/conf/zookeeper.conf
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaBrokerStarter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaService.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaStandalone.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaStandaloneStarter.java
Labels: release/2.7.0.x

#390 Avoid unexpected ConflictException when metadata is created
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: type/bug

#394 [ENHANCEMENT] perf tuning in decode phrase
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
Labels: type/enhancement

#398 to fix the NPE if TransactionCoordinator disabled
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Labels: type/bug

#400 Support OAUTHBEARER mechanism for KoP
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  kafka-impl/src/test/resources/kop-oauth2-another.properties
  kafka-impl/src/test/resources/kop-oauth2.properties
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthBearerTest.java
  tests/src/test/resources/kop-oauth2.properties
Labels: type/feature

#409 Fix SASL/PLAIN NPE caused by no OAuth2 config file
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthDefaultHandlersTest.java
  tests/src/test/resources/kop-default-oauth2.properties
Labels: type/bug
