Repository streamnative/kop, pull requests merged in 2021-08, with the labels that each got.

#627 Optimize the protocol handler start
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: type/enhancement

#636 Only allow topics under specific namespaces to be listed
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
Labels: type/feature

#632 Support Kafka consumer for Pulsar format messages when entryFormat is kafka
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Header.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
Labels: type/feature

#648 Support pulsar to obtain the correct unconfigured hostname listeners of KafkaProtocolHandler.
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
Labels: type/bug

#646 Allow setting listener name for topic lookup and optimize the lookup
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ConfigurationUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/feature

#659 Remove closed KafkaTopicConsumerManager from cache
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Labels: type/bug

#663 Avoid creating a lot of MetadataCache instances
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
Labels: type/bug, release/2.8.0.x

#673 Use pooled direct memory allocator when decoding Pulsar entry to Kafka records
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DirectBufferOutputStream.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/DirectBufferOutputStreamTest.java
Labels: type/enhancement

#692 [branch-2.8.0] Bump Pulsar to 2.8.0.15
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
  pom.xml
Labels: release/2.8.0.x

#693 [BUG] Fix unit test logs has multiple SLF4J bindings
  pom.xml
Labels: type/bug

#689 [BUGFIX] handle unsupported ApiVersionsRequest when channelPrepare
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
Labels: type/bug
