Repository streamnative/kop, pull requests merged in 2021-09, with the labels that each got.

#697 [BUGFIX] Fix go sarama client with v0 handshake can successful authenticated but will failed fresh metadata
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticatorTest.java
Labels: type/bug

#686 [FEATURE] Add commit offset test for Kafka clients of different versions
  kafka-0-10/src/main/java/io/streamnative/kafka/client/zero/ten/Consumer010Impl.java
  kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Consumer.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerConfiguration.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/TopicOffsetAndMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopRecordsUtil.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndPulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/DefaultKafkaClientFactory.java
Labels: type/feature

#695 Fix many non-durable cursors created on a topic with multiple groups
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerCache.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
Labels: type/bug

#709 [FEATURE] Support delay close on authentication failed
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ShutdownableThread.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DelayAuthorizationFailedCloseTest.java
Labels: type/feature, doc-required

#714 [FEATURE] Support close Idle connections when timeout
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIdleConnectionTest.java
Labels: type/feature

#719 Fix ACTIVE_CHANNEL_COUNT_INSTANCE decrement twice
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug

#722 Fix the findBroker method may hang
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
Labels: type/bug

#708 fetch.max.bytes and max.partition.fetch.bytes should be support!
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/feature

#712 [FEATURE] Add KopEventManager to repair metadata consistency of cluster and consistency of consumer group status
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/ChildChangeHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
Labels: type/feature

#733 [BUGFIX] Shut down KopEventManager when closing kop
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
Labels: type/bug

#735 Implement Tenant Aware Metadata Topics
  docs/configuration.md
  docs/security.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/KafkaPrincipal.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationKafkaMultitenantTenantMetadataTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java
Labels: type/feature, doc-required

#743 Invalidate KopBrokerLookupManager caches separately from GroupManagement listener
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
Labels: type/feature

#742 support multiple listeners with multiple endpoints
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/EndPointTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/feature, doc-required

#748 Adjust the log level
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimePulsarFormatTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestTypeTest.java
Labels: type/enhancement

#753 Fix producer and reader not close when GroupMetadataManager shutdown
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
Labels: type/bug

#755 Disable stats recorder for PulsarClient in group coordinator
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
Labels: type/enhancement

#758 [FEATURE] Add authorization to create topic and delete topic requests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java
Labels: type/feature

#752 [BUGFIX] Fix wrong broker cache with multiple listeners
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
Labels: type/bug

#767 [BUGFIX] Remove duplicated call skipBrokerEntryMetadataIfExist when parseMessageMetadata
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java
Labels: type/enhancement, release/2.8.1.x

#760 Update docs for multiple listeners and non-partitioned topic support
  docs/configuration.md
  docs/kop.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
Labels: doc
