Repository streamnative/kop, pull requests merged in 2021-02, with the labels that each got.

#361 Fix flaky testCreateInvalidTopics
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/bug

#364 Add docs for Envoy proxy
  README.md
  docs/envoy-proxy.md
Labels: area/Pulsar-doc, release/2.7.0.x

#365 [Transaction] Txn offset commit patch
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/offset/OffsetAndMetadata.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
Labels: type/enhancement

#263 kop using pulsar consumer metrics
  kafka-impl/conf/kop.conf
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ZooKeeperUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
Labels: triage/week-50, type/feature

#373 Fix outdated docs for prerequisite
  README.md
Labels: release/2.7.0.x

#372 Complete the ProducerIdManager component
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java
Labels: type/feature
