Repository streamnative/kop, pull requests merged in 2021-07, with the labels that each got.

#607 Fix group id z-node not updated for the same client id
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ZooKeeperUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: type/bug

#605 Add test framework for Kafka clients of different versions
  kafka-1-0/pom.xml
  kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
  kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ProducerImpl.java
  kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/package-info.java
  kafka-client-api/pom.xml
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Consumer.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerConfiguration.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ConsumerRecord.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Header.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ProduceContext.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/Producer.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ProducerConfiguration.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/RecordMetadata.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/ReflectionUtils.java
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/package-info.java
  kafka-client-factory/pom.xml
  kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactory.java
  kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/KafkaClientFactoryImpl.java
  kafka-client-factory/src/main/java/io/streamnative/kafka/client/api/package-info.java
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndPulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/DefaultKafkaClientFactory.java
Labels: release/2.8.0.x, type/feature

#610 Make build pass on JDK11
  kafka-1-0/pom.xml
  kafka-client-api/src/main/java/io/streamnative/kafka/client/api/KafkaVersion.java
Labels: type/enhancement

#621 [branch-2.7.2] Fix topic unload bug
  .github/workflows/pr-test.yml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetAcker.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: release/2.7.2.x, type/bug

#615 Remove unused maven repositories to speed up building
  pom.xml
Labels: release/2.8.0.x, type/enhancement

#620 Fix deadlock caused by KafkaTopicConsumerManager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Labels: release/2.8.0.x, type/bug

#626 [branch-2.7.2] Fix unused getList call to create missed partitions
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: release/2.7.2.x

#628 Speed up tests and fix flakiness
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/enhancement
