Repository streamnative/kop, pull requests merged in 2021-12, with the labels that each got.

#939 Add transaction config prefix
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaNonPartitionedTopicTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
Labels: release/2.8.1.x, release/2.9.0

#941 Transactions: implement support for JWT token authentication between brokers
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#946 Fix pulsar-io-thread block forever
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#951 Fix NPE problems caused by mockZooKeeper API changes when dump version to 2.8.1.26
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java
Labels: area/test, release/2.8.1.x, release/2.9.0

#953 Bump pulsar version to 2.8.1.0
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerTest.java
Labels: area/test, release/2.8.1.x

#943 Add Kafka payload processor
  kafka-payload-processor/pom.xml
  kafka-payload-processor/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaPayloadProcessor.java
  kafka-payload-processor/src/main/java/io/streamnative/pulsar/handlers/kop/package-info.java
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
Labels: type/feature, doc-required, release/2.9.0

#912 [Transaction] Support producer state manager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerAppendInfo.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateEntry.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DifferentNamespaceTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManagerTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#964 [BUGFIX] Fix the internal topics should be controlled in the meta namespace
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetConfig.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/TopicNameUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#947 Implement ability to not handle namespaces automatically: kafkaManageSystemNamespaces
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#976 Add cve_list md for CVE-2021-44228
  docs/cve_list.md
Labels: doc, release/2.8.1.x, release/2.9.0

#948 Refactor append records analyze and validate records
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeRequest.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopLogValidator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatterTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/NoHeaderKafkaEntryFormatter.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java
Labels: release/2.8.1.x, release/2.9.0

#980 Use Maven property instead of hard-coded version
  kafka-0-10/pom.xml
  kafka-0-9/pom.xml
  kafka-1-0/pom.xml
  kafka-2-8/pom.xml
  kafka-3-0/pom.xml
  kafka-client-factory/pom.xml
  kafka-payload-processor-shaded-tests/pom.xml
  kafka-payload-processor-shaded/pom.xml
Labels: release/2.8.1.x, release/2.9.1

#981 Migrating to sonatype new host
  pom.xml
Labels: area/build, release/2.8.1.x, release/2.9.1

#972 AdminManager: handle properly async deletePartitionedTopic
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
Labels: type/enhancement, release/2.9.1, release/2.8.2.x

#973 Fetch: trigger pending fetches when producing messages.
  docs/reference-metrics.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperation.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationPurgatory.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/enhancement, release/2.9.1, release/2.8.2.x

#991 Fix list topic and list offset behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug, release/2.9.1, release/2.8.2.x

#996 Add docs about how to use KafkaPayloadProcessor
  docs/configuration.md
Labels: doc, release/2.9.1

#989 Use pulsar AuthorizationService to authorize
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/KafkaPrincipal.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationMockTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizerTest.java
Labels: type/bug
