Repository streamnative/kop, pull requests merged in 2021-11, with the labels that each got.

#845 [FEATURE] Add message conversions metrics for prometheus metrics
  docs/reference-metrics.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/AbstractEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/ValidationAndOffsetAssignResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopLogValidator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/NoHeaderKafkaEntryFormatter.java
Labels: type/feature

#873 Disable transaction by default on units test
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: area/test, release/2.8.1.x, release/2.9.0

#869 [BUGFIX] Fix loadTxnLogTopics might crash in K8S environment
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#871 [Issue 867]: Implement minimal DeleteRecords (KStreams support)
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#878 support max.message.bytes
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#881 TransactionStateManager: improve loading mechanism
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#875 [Transaction] Migrate transaction coordinator handleInitProducerId tests and fix behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ErrorsAndData.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
Labels: type/bug, area/test, release/2.8.1.x, release/2.9.0

#884 [Docs] Add docs for KoP upgrade
  README.md
  docs/upgrade.md
Labels: doc, release/2.8.1.x, release/2.9.0

#885 [Transaction] Fix transaction coordinator handleAddPartitionsToTransaction behavior and migrate tests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#891 Speed up group coordinator tests
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
Labels: area/test, release/2.8.1.x, release/2.9.0

#892 Speed up group metadata manager test
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
Labels: area/test, release/2.8.1.x, release/2.9.0

#887 [Transaction] Fix transaction coordinator handleEndTransaction behavior and migrate tests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#890 [Transaction] Migrate remains of transaction coordinator handleInitProducerId tests and fix behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#894 Fix list offsets failure when ledgers are removed by a rollover operation
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinder.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#902 Implement dummy ALTER_CONFIGS and DESCRIBE_CONFIGS for Broker - minimal KSQL Server support
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#901 Make produce and fetch purgatory shared by all connections
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/enhancement, release/2.8.1.x, release/2.9.0

#898 [Docs] multiple listeners for KoP 2.9.0
  docs/configuration.md
Labels: doc, release/2.9.0

#895 [Transaction] Support transactional Id expiration
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionState.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#909 [Docs] Add docs for mixed_kafka format
  docs/configuration.md
Labels: doc, release/2.8.1.x, release/2.9.0

#905 [Transaction] Migrate transaction coordinator test and fix behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#911 [Docs] Add Monitor KoP link to main page
  README.md
  docs/kop.md
Labels: doc, release/2.8.1.x, release/2.9.0

#910 [Transaction] Fix transaction state manager might have race condition
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#907 Skip messages without BrokerEntryMetadata
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/MetadataCorruptedException.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetFinder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/OffsetSearchPredicate.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/UpgradeTest.java
Labels: type/enhancement, doc-required, release/2.8.1.x, release/2.9.0

#916 Add skipMessagesWithoutIndex option to enable skipping old messages
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/UpgradeTest.java
Labels: type/feature, doc-required, release/2.8.1.x, release/2.9.0

#922 [Docs] Add docs for skipMessagesWithoutIndex
  docs/upgrade.md
Labels: doc, release/2.8.1.x, release/2.9.0

#931 Avoid waiting a future when channel is closed
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
Labels: type/bug, release/2.8.1.x, release/2.9.0

#926 Adjust pom.xml for dependency management
  kafka-0-10/pom.xml
  kafka-0-10/src/main/java/io/streamnative/kafka/client/zero/ten/Consumer010Impl.java
  kafka-0-9/pom.xml
  kafka-0-9/src/main/java/io/streamnative/kafka/client/zero/nine/Consumer009Impl.java
  kafka-1-0/pom.xml
  kafka-1-0/src/main/java/io/streamnative/kafka/client/one/zero/ConsumerImpl.java
  kafka-2-8/pom.xml
  kafka-2-8/src/main/java/io/streamnative/kafka/client/two/eight/Consumer280Impl.java
  kafka-3-0/pom.xml
  kafka-3-0/src/main/java/io/streamnative/kafka/client/three/zero/Consumer300Impl.java
  kafka-client-api/pom.xml
  kafka-impl/pom.xml
  oauth-client/pom.xml
  pom.xml
  tests/pom.xml
Labels: area/build, release/2.8.1.x, release/2.9.0

#925 Split the message storage logic into independent classes
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedProduceAndFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/package-info.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopTopic.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/feature, release/2.8.1.x, release/2.9.0

#929 Improve TransactionMarkerChannelManager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
Labels: type/bug, release/2.8.1.x, release/2.9.0
