Repository streamnative/kop, pull requests merged in 2022-03, with the labels that each got.

#1126 Handle duplicate topic names requests in MetadataRequest
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2

#1138 Fix NPE when managed ledger find entry failed
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2

#1136 Avoid listing non-persistent topics and optimize the bundle listener
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicOwnershipListener.java
Labels: type/bug, type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2

#1140 Fix NOT_COORDINATOR error caused by wrong brokers in Metadata response
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug

#1148 Fix npe when update producer states
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2

#1152 KafkaMessageOrderKafkaTest: prevent spammy logs due to wrong entry in Kafka format received by the Pulsar consumer
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java
Labels: area/test, doc-info-missing

#1156 Fix when store group id failed the find coordinator future never complete
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2, doc-info-missing

#1163 Fix flaky testDeletePartition by sending to specific partitions
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
Labels: flaky-tests, release/2.8.2.x, release/2.10.0, release/2.9.2, doc-info-missing

#1165 Disable testIdempotentProducer for batch send
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
Labels: flaky-tests, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1176 Bump pulsar to 2.10.0.0-rc12 and fix testListOffsetForEmptyRolloverLedger
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
Labels: area/test, release/2.10.0, no-need-doc

#1150 [Docs] Fix the wrong implementation documents
  docs/implementation.md
Labels: doc, release/2.8.2.x, release/2.10.0, release/2.9.2

#1171 Refactor: remove static KafkaTopicConsumerManagerCache
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerCache.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManagerSharedState.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
Labels: flaky-tests, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1167 add send queue config for system client
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
Labels: type/feature, doc-required, release/2.8.2.x, release/2.10.0, release/2.9.2

#1174 Fix message disorder issue
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1144 Update tests with the correct way to configure multiple listeners
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: area/test, release/2.10.0, release/2.9.2

#1182 Do not boot default coordinators if kafkaManageSystemNamespaces is false
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
Labels: type/feature, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1180 fix client reconnect fail after bundle unload
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1170 Follow namespace configuration for Auto Topic Creation
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/feature, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1125 Transactions/Multi tenancy: use a Pulsar topic to generate Producer Ids
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PulsarStorageProducerIdManagerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionConfig.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PulsarStorageProducerIdManagerImplTest.java
Labels: type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2

#1195 [Docs] Describe how KoP reuses Pulsar's Authentication provider
  docs/security.md
Labels: doc, release/2.8.2.x, release/2.10.0, release/2.9.2

#1155 [Test] Change JUnit to TestNG
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/MemberMetadataTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/TestSSLUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/TestUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DelayAuthorizationFailedCloseTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIdleConnectionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/utils/timer/TimerTaskListTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/utils/timer/TimerTest.java
Labels: area/test, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1212 Fix handle offset commit fail when offset producer closed
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1153 Only set the policy when the kafka metadata namespace is first created
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1213 [security] Upgrade jackson-databind to get rid of CVE-2020-36518
  pom.xml
Labels: area/security, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1217 Drop the integration tests
  .github/workflows/pr-build-test-images.yml
  .github/workflows/pr-integration-tests.yml
  .github/workflows/push-build-test-images.yml
  integrations/README.md
  integrations/build.sh
  integrations/golang-confluent-kafka/Dockerfile
  integrations/golang-confluent-kafka/go.mod
  integrations/golang-confluent-kafka/go.sum
  integrations/golang-confluent-kafka/main.go
  integrations/golang-sarama/Dockerfile
  integrations/golang-sarama/go.mod
  integrations/golang-sarama/go.sum
  integrations/golang-sarama/main.go
  integrations/kafka-client/Dockerfile
  integrations/kafka-client/pom.xml
  integrations/kafka-client/src/main/java/Main.java
  integrations/kafka-client/src/main/resources/simplelogger.properties
  integrations/node-kafka-node/Dockerfile
  integrations/node-kafka-node/main.js
  integrations/node-kafka-node/package.json
  integrations/node-rdkafka/Dockerfile
  integrations/node-rdkafka/main.js
  integrations/node-rdkafka/package.json
  integrations/publish.sh
  integrations/python2-kafka-python/Dockerfile
  integrations/python2-kafka-python/produceConsume.py
  integrations/python2-pykafka/Dockerfile
  integrations/python2-pykafka/produceConsume.py
  integrations/rustlang-rdkafka/Cargo.lock
  integrations/rustlang-rdkafka/Cargo.toml
  integrations/rustlang-rdkafka/Dockerfile
  integrations/rustlang-rdkafka/src/main.rs
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIntegrationTest.java
Labels: type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc
