Repository streamnative/kop, pull requests merged in 2022-12, with the labels that each got.

#1600 [bugfix][transactions] TransactionMarkerChannelManager should not re-use the same variable
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Labels: type/bug, no-need-doc, release/2.9.3, release/2.8.4, release/2.10.2

#1601 Disable CodeCov annotation check in code review
  codecov.yml
Labels: no-need-doc

#1588 Update Kafka Client to 2.8.0
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/JoinGroupResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PendingRequest.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ResponseContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/metadata/ManagedLedgerPropertiesMigrationMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaRequestUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopLogValidator.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/KopResponseUtils.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/ListOffsetRequestV0.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallbackWrapper.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MockTime.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndKafkaTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DelayAuthorizationFailedCloseTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaIdleConnectionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndPulsarTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KTableTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/utils/timer/MockTime.java
Labels: no-need-doc, release/2.11

#1604 [fix] Use correct path for pulsar client TlsTrustCertsFilePath
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
Labels: no-need-doc

#1602 [fix] Use thread-safe list in TransactionMarkerChannelManager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Labels: no-need-doc

#1605 Fix flaky-test: PendingTopicFuturesTest#testExceptionalComplete
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
Labels: flaky-tests, no-need-doc, release/2.9.3, release/2.11, release/2.10.2

#1598 Transactions - reduce log level
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
Labels: no-need-doc

#1609 [flaky-test] Fix MultiLedgerTest.testListOffsetForEmptyRolloverLedger flaky test
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
Labels: no-need-doc

#1589 [feature] Support message publish rate limiting
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalServerCnx.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishThrottlingTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/PreciselyMessagePublishThrottlingTest.java
Labels: no-need-doc, release/2.9.3, release/2.11, release/2.10.2

#1603 [fix] Make ProducerIdManagerImpl thread safe
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImpl.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImplTest.java
Labels: no-need-doc

#1618 [fix] Recycle fetchRequest records when resultFuture already complete
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug, no-need-doc, release/2.9.3, release/2.11, release/2.10.2

#1619 [fix] Release leaked entries in getCommittedEntries
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
Labels: type/bug, no-need-doc

#1645 [bugfix] Fix regression with the upgrade to 2.8.x: Count corrently the number of partitions in ProduceRequest
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: no-need-doc

#1653 Remove usage of Scala classes from Kafka in tests
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
Labels: area/build, type/bug, no-need-doc, release/2.9.3, release/2.11, release/2.10.2

#1654 [branch-2.10] Use a more efficient implementation of sanitizeMetricName
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusStatsLogger.java
Labels: type/enhancement, release/2.9.3, release/2.10.2
