Repository streamnative/kop, pull requests merged in 2022-05, with the labels that each got.

#1269 [CI] Simplify the test workflow
  .github/workflows/pr-tests.yml
  .github/workflows/pr-unit-tests.yml
Labels: area/build, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1268 [transaction] Support write transaction marker when using oauth2 authentication
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionWithOAuthBearerAuthTest.java
Labels: type/bug, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1260 Implement OAuth2 client credentials flow
  docs/security.md
  oauth-client/pom.xml
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfig.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlow.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OAuthBearerTokenImpl.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthLoginCallbackHandler.java
  oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfigHelper.java
  oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfigTest.java
  oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlowTest.java
  oauth-client/src/test/resources/private_key.json
Labels: type/enhancement, doc, release/2.10.0, release/2.9.2, release/2.8.3

#1274 [Tests] Configure a different metadata namespace with the default namespace
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MultiLedgerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthDefaultHandlersTest.java
Labels: area/test, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1271 [bugfix][flaky-test] Fix handle produce request npe
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
Labels: release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1273 Fix compaction threshold not configured in metadata namespace
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetadataInitTest.java
Labels: type/bug, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1277 Separate LocalData and ThreadLocalAccessor from stats logger
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/DataSketchesOpStatsLogger.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LocalData.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/ThreadLocalAccessor.java
Labels: type/cleanup, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1276 Improve handle OAuth callback throw authentication exception behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
Labels: type/bug, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1280 Use self-generated jwk in OAuth units test
  ci/hydra/keys/private_key.json
  ci/hydra/keys/public_key.json
  ci/init_hydra_oauth_server.sh
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/HydraOAuthUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionWithOAuthBearerAuthTest.java
Labels: area/test, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1190 Metrics: expose per-tenant metrics
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
Labels: doc-required

#1282 Clean up errors sent to the client during Topic Unload
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
Labels: type/cleanup, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1285 Add useNativeGit to Git Commit Id Plugin - to support working with worktrees
  pom.xml
Labels: no-need-doc

#1060 Update Kafka Client to 2.1.1 and Disable Kafka 0.9 and 0.10 tests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaRequestUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthBearerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslPlainTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/saslplain/SaslPlainEndToEndTest.java
Labels: area/build

#1297 [Authorization] Remove unexpected produce permission validation
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
Labels: type/bug, flaky-tests, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1305 Add OAuth token refresh test
  ci/hydra/docker-compose.yml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
Labels: area/test, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1310 Rename most usages of "Oauth" to "OAuth"
  docs/security.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthBearerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthDefaultHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionWithOAuthBearerAuthTest.java
Labels: no-need-doc

#1307 Restore the support for Kafka clients 0.9 and 0.10
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaRequestUtils.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/ListOffsetRequestV0.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/saslplain/SaslPlainEndToEndTest.java
Labels: type/bug, no-need-doc

#1315 [Test] Ignore test change entry format unit test
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatterTest.java
Labels: no-need-doc
