Repository streamnative/kop, pull requests merged in 2022-11, with the labels that each got.

#1539 [Snyk] Upgrade sh.ory.hydra:hydra-client from 1.11.7 to 1.11.8
  tests/pom.xml
Labels: doc-info-missing

#1423 [improve] Trigger pending fetches when producing messages
  docs/reference-metrics.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/AppendRecordsContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallbackWrapper.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/MessageFetchContextTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/compatibility/BasicEndToEndTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java
Labels: type/feature, doc

#1556 [Snyk] Upgrade com.github.spotbugs:spotbugs-annotations from 3.1.8 to 3.1.12
  pom.xml
Labels: doc-info-missing, release/2.10.1, release/2.9.3, release/2.11

#1558 [Snyk] Security upgrade com.fasterxml.jackson.dataformat:jackson-dataformat-yaml from 2.13.4 to 2.14.0
  pom.xml
Labels: doc-info-missing, release/2.10.1, release/2.9.3, release/2.11

#1563 [improvement] Release PartitionResponse data as soon as possible
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
Labels: doc-info-missing

#1560 [fix][sec] Upgrade JacksonXML to 2.13.4.1 to get rid of CVE-2022-42003
  oauth-client/pom.xml
  pom.xml
Labels: doc-info-missing

#1561 [fix][sec] Upgrade protobuf-java to 3.19.6
  pom.xml
Labels: no-need-doc

#1562 [Snyk] Upgrade io.apicurio:apicurio-registry-schema-compatibility-json from 2.1.1.Final to 2.1.3.Final
  pom.xml
Labels: doc-info-missing

#1571 Fix lookup error when use simplified IPv6 address
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdvertisedListener.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopEventManager.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/AdvertisedListenerTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/EndPointTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
Labels: type/bug, no-need-doc

#1574 [branch-2.10.2] Add commons-validator dependency
  .github/workflows/pr-tests.yml
  kafka-impl/pom.xml
  pom.xml
Labels: no-need-doc

#1581 [feature] Allow to configure entryFormat per topic
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EncodePerformanceTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/PerTopicConfigurationTest.java
Labels: doc-required, release/2.11, release/2.10.2

#1587 [improve] Remove partition log when bundle unload
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TenantContextManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: no-need-doc
