Repository streamnative/kop, pull requests merged in 2022-02, with the labels that each got.

#1049 Fix thread safety issue for MessageFetchContext
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Labels: type/bug, type/enhancement, release/2.9.1, release/2.8.2.x, release/2.10.0

#1057 [Test] Fix flaky-test: DistributedClusterTest.testMultiBrokerProduceAndConsumeOnePartitionedTopic
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
Labels: area/test, release/2.9.1, release/2.8.2.x, release/2.10.0

#1055 [Test] Fix idempotent producer test
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: area/test, release/2.9.1, release/2.8.2.x, release/2.10.0

#1054 Return NOT_LEADER_FOR_PARTITION when managed ledger's state is wrong
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, release/2.9.1, release/2.8.2.x, release/2.10.0

#1061 Make ProducerIdManager an interface
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ProducerIdManagerImplTest.java
Labels: type/feature, release/2.8.2.x, release/2.10.0, release/2.9.2

#1063 Fix NPE during lookup during bundle unload
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
Labels: type/bug, release/2.10.0, release/2.9.2

#1064 Remove isMarkerMessage method in KoP MessagePublishContext
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
Labels: release/2.8.2.x, release/2.10.0, release/2.9.2

#1074 Bump Pulsar version to 2.10.0.0-rc2
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/InternalProducer.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java
Labels: area/build, release/2.10.0

#1084 Bump Pulsar version to 2.10.0.0-rc4
  kafka-payload-processor-shaded-tests/src/test/java/io/streamnative/pulsar/handlers/kop/MockedMessagePayloadContext.java
  pom.xml
Labels: area/build, release/2.10.0

#1092 Fix CreateTopics failure when kafkaAdvertisedListeners are different with kafkaListeners
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/EndPoint.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
Labels: type/bug, release/2.8.2.x

#1094 [Transaction] Able to disable transaction coordinator
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2

#1093 Optimize the way to get the controllerId
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/enhancement, release/2.10.0, release/2.9.2

#1103 [Authorization] List topic mapping to pulsar GET_TOPICS permission
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/Authorizer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/ResourceType.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2

#1106 add wenbingshen as maintainer
  README.md
Labels: doc

#1073 Transactions: don't create a thread per-tenant
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Labels: type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2

#1116 Fetch: do not decode data in critical BookKeeper OrderedExecutor thread
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
Labels: type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2

#1107 Refactor the handler for METADATA request
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/ListPair.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicAndMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/CoreUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/ListPairTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/CoreUtilsTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
Labels: type/enhancement, release/2.8.2.x, release/2.10.0, release/2.9.2

#1124 [flaky-test] Increase test idempotent produce timeout time
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
Labels: flaky-tests, release/2.8.2.x, release/2.10.0, release/2.9.2
