Repository streamnative/kop, pull requests merged in 2022-09, with the labels that each got.

#1468 Update the description of kopAllowedNamespaces
  docs/configuration.md
Labels: doc

#1469 [fix] Handle replicated subscription marker correct in pulsar entry formatter
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java
Labels: type/bug, no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3, release/2.11

#1473 [security] Upgrade snakeyaml to 1.31
  pom.xml
Labels: doc-info-missing

#1486 [Snyk] Upgrade io.fusionauth:fusionauth-jwt from 5.2.0 to 5.2.1
  pom.xml
Labels: doc-info-missing

#1493 [Transaction] Fix concurrent modification exception when broker close
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Labels: type/bug, no-need-doc, area/transaction

#1490 Bump Pulsar to 2.11.0.0-rc3 and use JDK17 for KoP
  .github/workflows/pr-tests.yml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: area/build, no-need-doc, release/2.11

#1497 Add codecov report
  .github/workflows/pr-tests.yml
  codecov.yml
  pom.xml
Labels: no-need-doc

#1501 [BUG#1500] Cannot submit offset correctly
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
Labels: doc-info-missing

#1504 [refactor][group] Simplify code and optimize loading partitions management
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
Labels: type/enhancement, no-need-doc, release/2.10.1, release/2.9.3, release/2.11, release/2.8.4

#1496 Log name of topic when topic not found
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: doc-info-missing, no-need-doc

#1512 Fix list offsets response wrong result
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java
Labels: type/bug, no-need-doc, release/2.10.1, release/2.9.3, release/2.11

#1505 Add migration handler and various code style fixes
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessor.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/http/package-info.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/migration/package-info.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/http/HttpRequestProcessorTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/migration/MigrationManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
Labels: no-need-doc, release/2.10.1, release/2.9.3, release/2.11, release/2.8.4
