Repository streamnative/kop, pull requests merged in 2022-04, with the labels that each got.

#1218 [Feature] Support set retention size limit for system namespace
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: doc-required, release/2.8.2.x, release/2.10.0, release/2.9.2

#1227 Update Codeowners
  .github/CODEOWNERS
Labels: doc-info-missing

#1228 Allow regular producers with a dedup enabled namespace
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
Labels: type/bug, release/2.8.2.x, release/2.10.0, release/2.9.2, no-need-doc

#1230 Fix authorization failed when using oauth2
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerToken.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredJws.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredValidatorCallbackHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerValidatorCallback.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
Labels: type/bug, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1234 [doc] add set retention size limit for system topic
  docs/configuration.md
Labels: doc, cherry-picked/branch-2.10.0, cherry-picked/branch-2.9.2, cherry-picked/branch-2.8.3

#1237 Support print full thread dump when the units test timeout
  kafka-impl/pom.xml
  kafka-payload-processor-shaded-tests/pom.xml
  oauth-client/pom.xml
  pom.xml
  test-listener/pom.xml
  test-listener/src/main/java/io/streamnative/pulsar/handlers/kop/common/test/TimeOutTestListener.java
  test-listener/src/main/java/io/streamnative/pulsar/handlers/kop/common/test/package-info.java
  tests/pom.xml
Labels: area/test, release/2.10.0, no-need-doc

#1244 Add authorization tests for OAuth2 authentication based on Hydra
  ci/init_hydra_oauth_server.sh
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersWithHydraServerTest.java
  tests/src/test/resources/oauth_credentials/simple_credentials_file.json
Labels: area/test, release/2.10.0, release/2.9.2, no-need-doc, release/2.8.3

#1249 Bump Pulsar to 2.10.0.1
  kafka-0-10/pom.xml
  kafka-0-9/pom.xml
  kafka-1-0/pom.xml
  kafka-2-8/pom.xml
  kafka-3-0/pom.xml
  kafka-client-api/pom.xml
  kafka-client-factory/pom.xml
  kafka-impl/pom.xml
  kafka-payload-processor-shaded-tests/pom.xml
  kafka-payload-processor-shaded/pom.xml
  kafka-payload-processor/pom.xml
  oauth-client/pom.xml
  pom.xml
  test-listener/pom.xml
  tests/pom.xml
Labels: no-need-doc

#1253 Exclude grpc package from pulsar-broker
  kafka-impl/pom.xml
  pom.xml
Labels: no-need-doc

#1241 Set default validate method value for OAuth
  docs/security.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ServerConfig.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ServerConfigTest.java
Labels: type/enhancement, doc, release/2.10.0, release/2.9.2, release/2.8.3

#1256 [Bugfix] Delete group id stored in metadata storage when consumer close
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: no-need-doc
