Repository streamnative/kop, pull requests merged in 2022-07, with the labels that each got.

#1360 Add KoP grafana dashboard
  grafana/README.md
  grafana/dashboard.json
  grafana/dashboard.png
Labels: doc

#1372 [Transaction] Fix wrong partition hash method in transaction state manager.
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
Labels: release/2.8.2.x, release/2.9.2, no-need-doc, release/2.10.1

#1375 [Bugfix] Find transaction coordinator should not store group ID
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: release/2.9.2, no-need-doc, release/2.8.3, release/2.10.1

#1388 [Transaction] Fix endless writing txn marker requests when the topic is deleted
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManagerTest.java
Labels: type/bug, release/2.9.2, no-need-doc, release/2.8.3, release/2.10.1, area/transaction

#1393 Fix linting errors in io.streamnative.pulsar.handlers.kop.coordinator.group
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/DelayedHeartbeat.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/DelayedJoin.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataConstants.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
Labels: type/bug, release/2.9.2, no-need-doc, release/2.8.3, release/2.10.1

#1394 Use `.equals()` instead of `==` for equality checks in GroupMetadata
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataTest.java
Labels: type/bug, release/2.9.2, no-need-doc, release/2.8.3, release/2.10.1

#1400 Fix linter warnings in GroupMetadataManager and GroupCoordinator
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
Labels: type/cleanup, release/2.9.2, no-need-doc, release/2.8.3, release/2.10.1

#1405 [improve] Make the LengthFieldPrepender singleton
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
Labels: no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1408 [improve] Make TransactionMarkerChannelInitializer LengthFieldPrepender singleton
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelInitializer.java
Labels: no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1410 Upgrade lombok to make KoP compatible with JDK 17
  pom.xml
Labels: type/enhancement, release/2.8.3, release/2.9.3

#1413 Fix transaction state update could be skipped for multiple transaction commits
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
Labels: type/bug, no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1404 [Refactor] Unify the pending inter-broker transaction requests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/CorrelationIdGenerator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PendingRequest.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/ResponseContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/KopRequestUtils.java
Labels: type/bug, type/enhancement, no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1414 [improve] Check the topic exists from cache
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManagerTest.java
Labels: type/enhancement, no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1417 [Transaction][branch-2.8.3] Fix endless writing txn marker requests when the topic is deleted
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManagerTest.java
Labels: type/bug, area/transaction

#1406 [Metrics] add cluster label to all kop metrics in Prometheus status logger
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusMetricsProvider.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: type/feature, no-need-doc, release/2.8.3, release/2.10.1, release/2.9.3

#1425 [CI] Cancel previous CI workflow if new commit pushed
  .github/workflows/pr-tests.yml
Labels: no-need-doc
