Repository streamnative/kop, pull requests merged in 2022-01, with the labels that each got.

#1005 [BUGFIX] Fix list topic behavior
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: type/bug, release/2.9.1, release/2.8.2.x

#1018 [Release] Fix javadoc missing bug
  kafka-payload-processor-shaded/pom.xml
Labels: type/bug, release/2.9.1

#1011 Implement placeholder 'advertisedAddress' in kafkaAdvertisedListeners
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
Labels: doc-required, release/2.9.1, release/2.8.2.x

#1016 [FEATURE] Add metric about the time spent on message conversions
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/AbstractEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/ValidationAndOffsetAssignResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KopLogValidator.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/NoHeaderKafkaEntryFormatter.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: type/enhancement, doc-required, release/2.9.1, release/2.8.2.x

#1021 Maintain a StatsLogger map to avoid creating new object every time
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MetricsProviderTest.java
Labels: type/bug, type/enhancement, release/2.9.1, release/2.8.2.x

#1026 [Docs] add conversions time nanos docs
  docs/reference-metrics.md
Labels: doc

#1034 Revert "Fetch: trigger pending fetches when producing messages. (#973)"
  docs/reference-metrics.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopServerStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperation.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/delayed/DelayedOperationPurgatory.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, release/2.9.1, release/2.8.2.x

#1037 Bump KoP version to 2.10.0-SNAPSHOT
  kafka-0-10/pom.xml
  kafka-0-9/pom.xml
  kafka-1-0/pom.xml
  kafka-2-8/pom.xml
  kafka-3-0/pom.xml
  kafka-client-api/pom.xml
  kafka-client-factory/pom.xml
  kafka-impl/pom.xml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  kafka-payload-processor-shaded-tests/pom.xml
  kafka-payload-processor-shaded/pom.xml
  kafka-payload-processor/pom.xml
  oauth-client/pom.xml
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetResetTest.java
Labels: area/build

#1042 fix create topic fail when using advertised listener
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaListenerNameTest.java
Labels: type/bug, release/2.9.1

#1044 Add docker compose example and docs for KoP standalone
  docker-compose.yml
  docs/kop.md
Labels: doc, release/2.9.1, release/2.10.0

#1006 [FEATURE] Reusing the Pulsar message deduplication
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerAppendInfo.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateEntry.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/IdempotentProducerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManagerTest.java
Labels: type/feature, doc-required, release/2.9.1, release/2.8.2.x, release/2.10.0
