Repository streamnative/kop, pull requests merged in 2023-01, with the labels that each got.

#1620 [improve] Transactions: use Epoll for eventLoopGroup when available
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
Labels: no-need-doc

#1626 [bugfix] Fix memory leak in case of closed connections with pending requests
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: no-need-doc

#1667 Remove unnecessary Boolean boxing
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusTextFormatUtil.java
Labels: no-need-doc

#1642 Optimize performance of EncodeResult.updateProducerStats and DecodeResult.updateConsumerStats
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/RequestStats.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusStatsLogger.java
Labels: no-need-doc

#1684 [docs] Add documents for KoP's Schema Registry
  README.md
  docs/configuration.md
  docs/kop.md
  docs/schema.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
Labels: doc, release/2.11

#1711 [performance] Remove dummy 10ms throttling on FetchResponse
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
Labels: no-need-doc, release/2.11, release/2.10.2, release/2.9.4
