Repository streamnative/kop, pull requests merged in 2023-03, with the labels that each got.

#1740 [docs] Update some outdated documents
  README.md
  docs/envoy-proxy.md
  docs/kop.md
Labels: doc, release/2.11, release/2.9.4, release/2.10.3

#1727 [improvement] Do not cache topics in KafkaTopicManagerSharedState
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManagerSharedState.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopEventManagerTest.java
Labels: no-need-doc

#1759 Fix the incompatibility with Pulsar 3.0.0.1-SNAPSHOT
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/AbstractEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaMixedEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/KafkaV1EntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/SaslAuthenticator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/PlainSaslServerTest.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/InnerTopicProtectionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandlerTest.java
Labels: area/build, no-need-doc

#1696 [ksqldb] Add implementation for describeCluster
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java
Labels: no-need-doc

#1757 [tests] Unflaky MessagePublishBufferThrottleTestBase
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  pom.xml
  tests/pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/MessagePublishBufferThrottleTestBase.java
  tests/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: no-need-doc

#1718 Improve OAuth documentation
  docs/security.md
Labels: doc

#1776 [improve] Add message.max.bytes for describe broker config
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: no-need-doc, release/2.11, release/2.9.4, release/2.10.3
