Repository streamnative/kop, pull requests merged in 2023-04, with the labels that each got.

#1784 Support passing the token directly as the password for Schema Registry
  docs/security.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
Labels: type/enhancement, doc, release/2.11

#1797 [fix][schema] Return JSON error message for failed request
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/ErrorMessage.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpJsonRequestProcessor.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpRequestProcessor.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/impl/SchemaStorageException.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/AbstractResource.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SubjectResource.java
  schema-registry/src/test/java/io/streamnative/pulsar/handlers/kop/schemaregistry/SchemaRegistryHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java
Labels: type/bug, no-need-doc, release/2.11

#1742 Improve getting started guide
  docker-compose-cluster.yaml
  docs/kop.md
Labels: doc

#1793 [test] Add kafka admin api unit test
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAdminTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: no-need-doc

#1801 Return a correct metadata response when topic is not found
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicAndMetadata.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, no-need-doc, release/2.11, release/2.9.4, release/2.10.3

#1802 [Schema] Return 401 error when no HTTP authentication is configured
  pom.xml
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/HttpJsonRequestProcessor.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaAuthorizationTestBase.java
Labels: type/bug, no-need-doc

#1805 [Schema Registry] Fix the delete operation not work
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryManager.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/impl/PulsarSchemaStorage.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRestApiTest.java
Labels: type/bug, no-need-doc, release/2.11

#1822 Upgrade the Pulsar version to 3.0.0.1-rc1
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/DecodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EncodeResult.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LongAdderCounter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/NullStatsLogger.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java
Labels: no-need-doc, release/3.0

#1826 [Schema] Fix wrong response when querying schema by subject and version
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/model/Schema.java
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SubjectResource.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRegistryTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SchemaRestApiTest.java
Labels: type/bug, no-need-doc, release/2.11, release/3.0
