Repository streamnative/kop, pull requests merged in 2023-08, with the labels that each got.

#1989 [CI] Upload surefire artifacts when tests failed
  .github/workflows/pr-tests.yml
Labels: area/test, no-need-doc, release/2.11, release/3.0

#1990 [improve][oauthclient] Support decode base64 format credentials URL
  oauth-client-shaded-test/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfigTest.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientConfig.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/DataURLStreamHandler.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/PulsarURLStreamHandlerFactory.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/URL.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/url/package-info.java
Labels: area/security, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1966 [fix][transaction] Fix some tests and clean up logs
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/KopDataOutputStreamWritable.java
  test-listener/pom.xml
  test-listener/src/main/java/io/streamnative/pulsar/handlers/kop/common/test/TimeOutTestListener.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/e2e/DistributedClusterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/e2e/MultiLedgerTest.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1992 Fix wrong offset increment for Sarama message set
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLogTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/SaramaCompressedV1Records.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1991 [Transaction] Fix initTransaction might wait until request timeout
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java
Labels: type/bug, no-need-doc, area/transaction, release/2.11, release/3.0

#1981 Update Kafka wire protocol to 3.4.0 and implement KIP-699 and KIP-709
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/exceptions/KoPTopicInitializeException.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/KafkaResponseUtils.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageMetadataUtils.java
  kafka-impl/src/main/java/org/apache/kafka/common/requests/ResponseCallbackWrapper.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterTest.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/EntryPublishTimeKafkaFormatTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaCommonTestUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerWithAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/admin/KafkaAdminTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/e2e/DistributedClusterTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/metrics/MetricsProviderTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/GlobalKTableTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KStreamAggregationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KTableTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/streams/KafkaStreamsTestBase.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1977 [fix][transaction] Handle some failures in transaction
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManager.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1993 [fix][transaction] Contains UUID when auto topic creation
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AdminManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
Labels: type/bug, no-need-doc, area/transaction, release/2.11, release/3.0

#1995 Fix topic lookup failed exceptionally with ServiceUnitNotReady
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicLookupService.java
Labels: type/bug, no-need-doc

#1996 Add Time based metric exipration.
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/DataSketchesOpStatsLogger.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/LocalData.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/PrometheusMetricsProvider.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/ThreadLocalAccessor.java
Labels: type/bug, no-need-doc

#1994 [fix][transaction] Use pulsar format when write marker to __consumer_offsets topic
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/EntryFormatterFactory.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtilsTest.java
Labels: no-need-doc, area/transaction

#1999 Optimize authorization by caching authorization results
  docs/configuration.md
  kafka-impl/pom.xml
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfigurationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaAuthorizationMockTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaAuthorizationMockTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/SlowAuthorizationTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/SaslOAuthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/SaslOAuthKopHandlersWithMultiTenantTest.java
Labels: type/enhancement, no-need-doc
