Repository streamnative/kop, pull requests merged in 2023-05, with the labels that each got.

#1833 Fix javadoc plugin configuration version
  pom.xml
Labels: no-need-doc, release/2.11, release/3.0

#1834 Upgrade org.json and kaml to non vulnerable versions
  pom.xml
Labels: doc-info-missing, release/2.11, release/2.10.4, release/3.0

#1839 Fix pulsar entry formatter encode zero timestamp record caused exception
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/PulsarMessageBuilder.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1809 [improve] Enable transaction and schema registry on docker compose
  docker-compose-cluster.yaml
  docker-compose.yml
Labels: no-need-doc, release/2.11, release/3.0

#1848 Use brokerClientTlsEnabled to configure pulsar client
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1853 Fix flaky-test: KafkaNonPartitionedTopicTest.testNonPartitionedTopic
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaNonPartitionedTopicTest.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0, release/branch-2.9.5

#1856 [fix] Fix read unstable messages
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/TransactionTest.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1855 [Snyk] Security upgrade io.streamnative:pulsar-broker from 3.0.0.1-rc1 to 3.0.0.1
  pom.xml
Labels: doc-info-missing, release/3.0

#1841 [feat][schema] Support getting schema string by id
  schema-registry/src/main/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SchemaResource.java
  schema-registry/src/test/java/io/streamnative/pulsar/handlers/kop/schemaregistry/resources/SchemaResourceTest.java
Labels: type/enhancement, no-need-doc, release/2.11, release/3.0

#1868 [bugfix][transactions] Prevent ConcurrentModificationException in getProducer()
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1864 fix: remove topic.getManagedLedger().asyncDeleteCursor
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1869 [bugfix][transactions] Make TxnTransitMetadata.topicPartitions immutable
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMetadata.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManagerTest.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0
