Repository streamnative/kop, pull requests merged in 2023-06, with the labels that each got.

#1867 [bugfix][transactions] Release memory in TransactionMarkerChannelHandler
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
Labels: no-need-doc, release/2.11, release/3.0

#1878 [improve] Get size from byteBuf earlier to prevent unnecessary retention
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PartitionLog.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1888 [bugfix] Fix decode pulsar format batch records timestamp
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/BasicEndToEndPulsarTest.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1883 [fix][transaction] TransactionMarkerRequestCompletionHandler retries on UNKNOWN_SERVER_ERROR
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1890 [perf][improvement] Improvements for PulsarEntryFormatter
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/PulsarMessageBuilder.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1895 [debug] add better log for CONCURRENT_TRANSACTIONS error
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0

#1887 [refactor] Decoupling the offset topic I/O from GroupMetadataManager
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/SystemTopicClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopic.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataConstants.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/package-info.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/CoreUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupCoordinatorTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManagerTest.java
Labels: type/enhancement, no-need-doc, release/2.11, release/3.0

#1898 [fix] not respone for PRODUCE when acks=0
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ReplicaManager.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaApisTest.java
Labels: type/bug, no-need-doc, release/2.11, release/2.10.4, release/3.0

#1903 Fix flaky CompactedPartitionedTopicTest.testClose
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java
Labels: flaky-tests, no-need-doc, release/2.11, release/3.0

#1899 [improvements] Use the TopicEventListener API
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicConsumerManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/NamespaceBundleOwnershipListenerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicEventListenerImpl.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/TopicOwnershipListener.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CacheInvalidatorTest.java
Labels: type/enhancement, no-need-doc, release/3.0

#1905 Reduce the offset commit timeout to 5 seconds and make it configurable
  docs/configuration.md
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaServiceConfiguration.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopic.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadataManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/OffsetConfig.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetTopicWriteTimeoutTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/CompactedPartitionedTopicTest.java
Labels: type/feature, doc, release/2.11, release/3.0

#1906 [transaction] Producer state manager snapshot recovery - Part-1: Add snapshot I/O buffer
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManagerSnapshot.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManagerSnapshotBuffer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PulsarPartitionedTopicProducerStateManagerSnapshotBuffer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/storage/PulsarTopicProducerStateManagerSnapshotBuffer.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/ProducerStateManagerSnapshotBufferTestBase.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PulsarPartitionedTopicProducerStateManagerSnapshotBufferTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/storage/PulsarTopicProducerStateManagerSnapshotBufferTest.java
Labels: no-need-doc, release/2.11, release/3.0

#1914 Fix flaky OffsetTopicWriteTimeoutTest
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/OffsetTopicWriteTimeoutTest.java
Labels: flaky-tests, no-need-doc, release/2.11, release/3.0

#1907 [transactions] Better handling of network exceptions while sending TX markers
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PendingRequest.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionCoordinator.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerChannelHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionMarkerRequestCompletionHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/TransactionStateManager.java
Labels: no-need-doc, area/transaction, release/2.11, release/2.10.4, release/3.0

#1893 [improvement] Remove expensive useless String.format() in canConsumeAsync
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/auth/SimpleAclAuthorizer.java
Labels: no-need-doc, release/2.11, release/2.10.4, release/3.0
