Repository streamnative/kop, pull requests merged in 2023-02, with the labels that each got.

#1694 [Doc] - Add entryFormat description and performance test class
  docs/configuration.md
Labels: doc

#1720 [cleanup] Remove static LOOKUP_CLIENT_MAP
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaChannelInitializer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/LookupClient.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManagerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KopProtocolHandlerTestBase.java
Labels: type/cleanup, no-need-doc, area/transaction, release/2.11, release/2.9.4, release/2.10.3

#1722 [bugfix] Fix NPE in PendingTopicFutures and fix KafkaMessageOrderTestBase
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/PendingTopicFutures.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/PendingTopicFuturesTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java
Labels: type/bug, no-need-doc, release/2.11, release/2.9.4, release/2.10.3

#1728 Add multi-tenant support for OAuth authentication
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerSaslServer.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerToken.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredJws.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/KopOAuthBearerUnsecuredValidatorCallbackHandler.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OAuthTokenDecoder.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandler.java
  kafka-impl/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/OAuthTokenDecoderTest.java
  oauth-client/pom.xml
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlow.java
  oauth-client/src/main/java/io/streamnative/pulsar/handlers/kop/security/oauth/OAuthBearerTokenImpl.java
  oauth-client/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/ClientCredentialsFlowTest.java
  oauth-client/src/test/resources/private_key.json
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/CustomOAuthBearerCallbackHandlerTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/HydraOAuthUtils.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOAuthKopHandlersWithMultiTenantTest.java
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/oauth/OauthValidatorCallbackHandlerTest.java
  tests/src/test/resources/credentials_file.json
Labels: type/feature, doc-required, release/2.11, release/2.10.3

#1731 [tests] Prevent test timeouts due to pulsar client hanging while shutdown
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/AbstractPulsarClient.java
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java
Labels: no-need-doc

#1734 Fix the compatibility issue with Pulsar 2.11.0
  kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/ByteBufUtils.java
  pom.xml
  tests/src/test/java/io/streamnative/pulsar/handlers/kop/coordinator/transaction/PulsarStorageProducerIdManagerImplTest.java
Labels: type/bug, no-need-doc, release/2.11

#1741 Upgrade nexus staging maven plugin
  pom.xml
Labels: no-need-doc, release/2.11
